#### general settings
name: dan_rrdb_ema
scale: 4
save: true
gpu_ids: [0, 1, 2, 3]

model:
  type: DegSRModel

evaluation:
  metrics: [psnr, ssim]
  lpips_type: alex
  max_value: 255
  crop_border: 4
  cuda: true

#### datasets
datasets:
  train:
    name: DIV2K
    mode: SingleImageDataset
    data_type: lmdb
    color: RGB
    ratio: 256

    dataroot: /home/lzx/SRDatasets/DF2K/HR/x4.lmdb

    use_shuffle: true
    workers_per_gpu: 4  # per GPU
    imgs_per_gpu: 16
    img_size: 192
    use_flip: true
    use_rot: true

  val:
    name: DIV2KMD
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_src: /home/lzx/SRDatasets/DIV2K_valid/deg/DIV2K_Real_mini.lmdb
    dataroot_tgt: /home/lzx/SRDatasets/DIV2K_valid/HR/x4_mini.lmdb

#### network structures
networks:
  netDeg1:
    which_network: Degrader
    setting:
      deg_scale: 4
      crop_size: ~
      return_ratio: true
      blur_opt: 
        ksize: 21
        range_radius: [3, 11]
        range_x: [0.2, 3]
        range_y: [0.2, 3]
        range_t: [0, 0.5]
        range_betag: [0.5, 4]
        range_betap: [1, 2]
        iso_prob: 0.7
        generalized_prob: 0.15
        gaussian_prob: 0.85
        sinc_prob: 0.1
      resize_opt:
        range_scale: [0.15, 1.5]
        up_prob: 0.2
        down_prob: 0.7
        resize_mode: ["area", "bicubic", "bilinear"]
        mode_prob: [0.333, 0.334, 0.333]
        base: src
      noise_opt:
        range_g: [1, 30]
        range_p: [0.05, 3]
        gray_prob: 0.4
        gauss_prob: 0.5
      jpeg_opt:
        range_q: [30, 95]
        jpeg_prob: 0.5

  netDeg2:
    which_network: Degrader
    setting:
      deg_scale: 4
      crop_size: ~
      return_ratio: true
      blur_opt: 
        ksize: 21
        range_radius: [3, 11]
        range_x: [0.2, 1.5]
        range_y: [0.2, 1.5]
        range_t: [0, 0.5]
        range_betag: [0.5, 4]
        range_betap: [1, 2]
        iso_prob: 0.7
        generalized_prob: 0.15
        gaussian_prob: 0.85
        sinc_prob: 0.1
      noise_opt:
        range_g: [1, 25]
        range_p: [0.05, 2.5]
        gray_prob: 0.4
        gauss_prob: 0.5
      resize_opt:
        range_scale: [0.3, 1.2]
        up_prob: 0.3
        down_prob: 0.4
        resize_mode: ["area", "bicubic", "bilinear"]
        mode_prob: [0.333, 0.334, 0.333]
        base: tgt
      resize_back_opt:
        ksize: 21
        range_radius: [3, 11]
        sinc_prob: 0.8
        resize_mode: ["area", "bicubic", "bilinear"]
        mode_prob: [0.333, 0.334, 0.333]
      jpeg_opt:
        range_q: [30, 95]
        jpeg_prob: 0.5
        
  netSR:
    which_network: DAN
    setting:
      block: rrdb
      est_size: large
      nc: 3
      nf: 64
      nb: 16
      deg_dim: 42
      scale: 4
      loop: 3
    pretrain: 
      path: ~
      strict_load: true
  
#### training settings: learning rate scheme, loss
train:
  resume_state: ~
  manual_seed: ~
  queue_size: 256
  ema_decay: 0.999

  niter: 600000
  warmup_iter: -1  # no warm up

  losses:
    sr_pix:
      type: L1Loss
      weight: 1.0
    
    deg_reg:
      type: MSELoss
      weight: 1.0
    
  optimizers:
    netSR:
      type: Adam
      lr: !!float 2e-4
  
  schedulers:
    default:
      type: MultiStepRestartLR
      milestones: [300000, 500000]
      gamma: 0.5

validation:
  val_freq: !!float 5e3
  save: true

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: false

